### ISSUE TITLE
Bubble sort code review

### ISSUE THREAD

**Issue by Gracetemitope** [jadx2/bubble_sort#2]

**Comment by george-shammar** [comment]
Nice job.

**Comment by Gracetemitope** [comment]
Weldone!

**Comment by NoTengoBattery** [comment]
A non-code related reflection
===

While I like the approach, you have to remember this (is a good lesson for the future, believe me).

In this particular case, the code is pretty small, and the impact is negligible. But remember that you write code for humans first and the computer second. Ruby is not an obscure, weird-syntax language like Shell, Make, or M4. Ruby is designed to look beautiful and be easy to read. In theory, you should be able to read a Ruby program like reading an English text.

I am not telling you that the code is bad, or it looks ugly. My suggestion is to try to be a little bit more verbose. This means: add more meaningful variable names, break complex one-liners into smaller and successive operations, and learn more about some (syntactic sugar)[https://en.wikipedia.org/wiki/Syntactic_sugar] that the language offers to make it more readable.

This little reflection can save you a headache or two. For example, most step-by-step debuggers may not break one-liners into smaller logical steps, making the task of pinpointing a failed execution harder, probably forcing you to break the one-liner into smaller chunks and restart the debugging session. That is wasted time.

Think into the future, make code that can be easily maintained, you don't know if a year later you may need to debug legacy code, and by that time you already forgot what the variable `a` does or where the variable `b` is changed, or what a huge one-liner is supposed to do.

**Comment by george-shammar** [comment]
Oever's comment above is noteworthy. I'll take it to heart personally in my future projects. Thanks Oever.
